[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Jyri-Matti Lähteenmäki"
Model = "Spot"
Name = "Spot"
SerialNumber = "AA:AA:AA:AA:AA:DD"
FirmwareRevision = "100.1.1"


[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Sähkön Spot-hinta"
[services.characteristics.CurrentTemperature]
cmd = "cd spot; ./cmd/currentPrice.sh"
