bridge = "spot"
port = 12304
username = "AA:AA:AA:AA:AA:04"

[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Jyri-Matti Lähteenmäki"
Model = "Spot"
Name = "Spot"
SerialNumber = "AA:AA:AA:AA:AA:04"
FirmwareRevision = "100.1.1"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Sähkön Spot-hinta"
ConfiguredName = "Sähkön Spot-hinta"
[services.characteristics.CurrentTemperature]
minValue = -99
minStep = 0.001
cmd = "cd spot; ./cmd/currentPrice.sh"
